layout_spectrum: 0.9336917
color:
  saturation: 1
  lightness: 1
  brandStrength: 0.4960816
  brandColors:
    - '#1F0201'
    - '#FCFBFA'
    - '#C5BDBE'
    - '#EAAB89'
    - '#A35331'
  rhythmicContrast: 0.6738351
typography_spectrum: 0.3727598
name: Linda Garcia
