name: Linda Garcia
favicon: null
layout_spectrum: 0.9336917
typography_spectrum: 0.3727598
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: Happy Free Love
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#838384'
    - '#000000'
    - '#555555'
    - '#404040'
    - '#999999'
  brandStrength: 0.4960816
  lightness: 1
  saturation: 1
  rhythmicContrast: 0.6738351
purpose: []
